name: Build and Upload Binaries

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build binary
        run: |
          python PhraseCraft/build_phrasec.py
        env:
          PYTHONPATH: ${{ github.workspace }}
          REPO_PATH: ${{ github.workspace }}

      - name: Archive Linux binary
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          zip -j ${{ github.workspace }}/linux_binary.zip ${{ github.workspace }}/dist/phrasec
        env:
          REPO_PATH: ${{ github.workspace }}

      - name: Archive Windows binary
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          powershell Compress-Archive -Path "$Env:REPO_PATH\PhraseCraft\dist\phrasec" -DestinationPath "$Env:REPO_PATH\windows_binary.zip"
        env:
          REPO_PATH: ${{ github.workspace }}

      - name: Upload Linux binary
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: linux-binary
          path: ${{ github.workspace }}/linux_binary.zip

      - name: Upload Windows binary
        if: ${{ matrix.os == 'windows-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: ${{ github.workspace }}/windows_binary.zip
