name: Build phrasecraft CLI Executable

on:
  push:
    branches:
      - main  # Trigger build on push to main branch
  pull_request:
    branches:
      - main  # Trigger build on pull request to main branch

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Build for both Linux and Windows
    
    steps:
      # 1. Checkout code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. Set up Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      
      # 3. Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Correct path to requirements.txt at the root

      # 4. Install PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller  # Install PyInstaller for building the executable
      
      # 5. Debugging: List contents of the current directory before building
      - name: List current directory contents before build
        run: |
          ls -l
      
      # 6. Build the executable using PyInstaller
      - name: Build phrasecraft executable
        run: |
          pyinstaller --onefile --name phrasec --add-data "PhraseCraft/eef_wordlist.txt:." PhraseCraft/phrasec.py

      # 7. Debugging: List contents of the dist folder after build
      - name: List contents of dist folder after build
        run: |
          ls -l PhraseCraft/dist/
      
      # 8. Upload the built executables as artifacts
      - name: Upload Executable
        uses: actions/upload-artifact@v3  # Using the latest v3 version of upload-artifact
        with:
          name: phrasecraft-executable-${{ matrix.os }}
          path: PhraseCraft/dist/phrasec*   # Matches both phrasec (Linux) and phrasec.exe (Windows)
